spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bluelogistic
    username: bluelogistic
    password: bluelogistic123
  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG